codecov:
  branch: main
  token: c14be219-3495-4039-8cbf-3f6dc4e76eac

fixes:
  # Fix the file names:
  - "/opt/hostedtoolcache/Python/*/x64/lib/python*/site-packages/::"
  - "/Users/runner/hostedtoolcache/Python/*/x64/lib/python*/site-packages/::"

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 100%
        threshold: 0%
        branches: null

    patch:
      default:
        target: 100%
        threshold: 0%
        branches: null

    changes: false
      # I don't understand these, so turning it off...
      #default:
        #branches: null

  ignore: null

comment: false
  # I find these more annoying than helpful, so turning them off.
  #layout: "header, diff, changes, sunburst, uncovered, tree"
  #branches: null
  #behavior: default
