codecov:
  branch: master

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 100%
        threshold: 0%
        branches: null

    patch:
      default:
        target: 100%
        threshold: 0%
        branches: null

    changes: false
      # I don't understand these, so turning it off...
      #default:
        #branches: null

  ignore: null

comment: false
  # I find these more annoying than helpful, so turning them off.
  #layout: "header, diff, changes, sunburst, uncovered, tree"
  #branches: null
  #behavior: default
