# vim: set filetype=python :

import os
import glob

Import('env')
ReadFileList=env['__readfunc']
DoPythonConfig=env['_DoPythonConfig']
pyenv = env.Clone()

DoPythonConfig(pyenv)

for d in ['SBProfile']:
    SConscript(os.path.join(d, 'SConscript'), exports='pyenv')
