# vim: set filetype=python :

import os
Import('env')

RunInstall = env['_InstallProgram']
RunUninstall = env['_UninstallProgram']

for fname in ['GalSim.table']:

    cfile=env.File(fname)
    install_subdir = 'ups'
    targets = [cfile]

    if 'install' in COMMAND_LINE_TARGETS:
        RunInstall(env, targets, install_subdir)

    if 'uninstall' in COMMAND_LINE_TARGETS:
        RunUninstall(env, targets, install_subdir)
