#!/bin/bash

# Copyright 2012, 2013 The GalSim developers:
# https://github.com/GalSim-developers
#
# This file is part of GalSim: The modular galaxy image simulation toolkit.
#
# GalSim is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# GalSim is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GalSim.  If not, see <http://www.gnu.org/licenses/>
#

python=../bin/installed_python  # For python scripts
bin=../bin  # For galsim executable

if [ ! -d "output" ]; then
    mkdir output
fi
if [ ! -d "output_yaml" ]; then
    mkdir output_yaml
fi

/bin/rm -rf output/DECam*
/bin/rm -rf output_yaml/DECam*

time $python des.py || exit
time $bin/galsim -m des -v1 des.yaml || exit

echo 'Checking diffs:'

cd output
for f in $(ls DECam*.fits)
do
    echo diff -q $f ../output_yaml/$f
    diff -q $f ../output_yaml/$f
done
