#!/bin/bash

# Copyright 2012, 2013 The GalSim developers:
# https://github.com/GalSim-developers
#
# This file is part of GalSim: The modular galaxy image simulation toolkit.
#
# GalSim is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# GalSim is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GalSim.  If not, see <http://www.gnu.org/licenses/>
#

bin1=../bin  # For python scripts
bin2=../bin  # For galsim_json executable

if [ ! -d "output" ]; then
    mkdir output
fi
if [ ! -d "output_json" ]; then
    mkdir output_json
fi

/bin/rm -rf output/*
/bin/rm -rf output_json/*

time $bin1/demo1 || exit
time $bin2/galsim_json json/demo1.json || exit

time $bin1/demo2 || exit
time $bin2/galsim_json json/demo2.json || exit

time $bin1/demo3 || exit
time $bin2/galsim_json json/demo3.json || exit

time $bin1/demo4 || exit
time $bin2/galsim_json json/demo4.json || exit

time $bin1/demo5 || exit
time $bin2/galsim_json json/demo5.json || exit

time $bin1/demo6 || exit
time $bin2/galsim_json json/demo6a.json json/demo6b.json || exit

time $bin1/demo7 || exit
time $bin2/galsim_json json/demo7.json || exit

time $bin1/demo8 || exit
time $bin2/galsim_json json/demo8a.json json/demo8b.json || exit

time $bin1/demo9 || exit
time $bin2/galsim_json json/demo9.json || exit

time $bin1/demo10 || exit
time $bin2/galsim_json json/demo10.json || exit

time $bin1/demo11 || exit
time $bin2/galsim_json json/demo11.json || exit

echo 'Checking diffs: (No output means success)'

# demo1:
# Don't check demo1, since it doesn't use a deterministic seed.
# If you add an initial seed in both places, then you can uncomment 
# the next line and it should work.
#diff -q output/demo1.fits output_json/demo1.fits 

# demo2:
diff -q output/demo2.fits output_json/demo2.fits 

# demo3:
diff -q output/demo3.fits output_json/demo3.fits 
diff -q output/demo3_epsf.fits output_json/demo3_epsf.fits 

# demo4:
diff -q output/multi.fits output_json/multi.fits 

# demo5:
diff -q output/g08_psf.fits output_json/g08_psf.fits
diff -q output/g08_gal.fits output_json/g08_gal.fits

# demo6:
diff -q output/psf_real.fits output_json/psf_real.fits
diff -q output/cube_real.fits output_json/cube_real.fits 

# demo7:
# Note; the raw .gz files include the filename in them.
# Since the file names are different, they don't match.
# So unzip them first before running diff.
gunzip output/cube_phot.fits.gz
gunzip output_json/cube_phot.fits.gz
diff -q output/cube_phot.fits output_json/cube_phot.fits

# demo8:
diff -q output/bpd_single.fits output_json/bpd_single.fits 
diff -q output/bpd_multi.fits output_json/bpd_multi.fits 

# demo9:
for dir_num in {1..4} 
do
    for file_num in {0..4}
    do
        file_name=nfw$dir_num/cluster000$file_num.fits
        diff -q output/$file_name output_json/$file_name
    done
done

# demo10:
diff -q output/power_spectrum.fits output_json/power_spectrum.fits 

# demo11:
diff -q output/tabulated_power_spectrum.fits.fz output_json/tabulated_power_spectrum.fits.fz 
