#!/usr/bin/env python

import sys
import subprocess

cmd = "diff -q %s %s"%(tuple(sys.argv[1:]))
p = subprocess.Popen([cmd],stdout=subprocess.PIPE, stderr=subprocess.STDOUT, shell=True)
diff_output = p.stdout.read()

if len(diff_output) > 0:
    print diff_output.strip()

    try:
        try:
            import astropy.io.fits as pyfits
        except:
            import pyfits
    except ImportError as e:
        # Then /usr/bin/env python doesn't have pyfits installed.  Oh well.
        sys.exit()

    try:
        f1 = pyfits.open(sys.argv[1])
        f2 = pyfits.open(sys.argv[2])
    except IOError as e:
        # Then at least one of the files doesn't exist, which diff will have already reported.
        sys.exit()

    for hdu in range(len(f1)):
        d0 = f1[hdu].data
        d1 = f2[hdu].data
        if (d0 != d1).any():
            print '    HDU %d shows differences in %d pixels'%(hdu, (d0!=d1).sum())
            print '    The maximum absolute difference is %e.'%(abs(d0-d1).max())
            print '    The maximum relative difference is %e.'%(abs((d0-d1)/(d0+1.e-10)).max())
