import galsim

k0 = galsim._galsim.PositionD(0, 0)
ser = galsim.SBSersic(2, 2)
ser_shear = ser.shear(0.2, 0.2)
box = galsim.SBBox(0.2)
c1 = galsim.SBConvolve(ser)
c1.add(box)
img1 = c1.draw()
c2 = galsim.SBConvolve(ser_shear)
c2.add(box)
img2 = c2.draw()
print "Unsheared sersic min/max:", img1.array.min(), img1.array.max()
print "Unsheared sersic flux:", ser.getFlux()
print "Unsheared sersic value at k origin:", ser.kValue(k0)
print "Sheared sersic min/max:", img2.array.min(), img2.array.max()
print "Sheared sersic flux:", ser_shear.getFlux()
print "Sheared sersic value at k origin:", ser_shear.kValue(k0)
print "Box flux:", box.getFlux()
print "Box value at k-origin:", box.kValue(k0)
print "Convolution 1 flux:", c1.getFlux()
print "Convolution 1 value at k origin:", c1.kValue(k0)
print "Convolution 2 flux:", c2.getFlux()
print "Convolution 2 value at k origin:", c2.kValue(k0)

