// -*- c++ -*-
#ifndef SBPROFILE_H
#define SBPROFILE_H

/** 
 * @file SBProfile.h @brief Contains a class definition for two-dimensional Surface Brightness 
 * Profiles.
 *
 * The SBProfiles include common star, galaxy, and PSF shapes.
 * If you have not defined USE_LAGUERRE, the SBLaguerre class will be skipped.
 * If you have not defined USE_IMAGES, all of the drawing routines are disabled but you will no 
 * longer be dependent on the Image and FITS classes.
 */

#include <cmath>
#include <list>
#include <map>
#include <vector>
#include <algorithm>

/**
 * Remove this to disable the drawing routines. Also removes dependencies on Image and FITS classes.
 */
#define USE_IMAGES 

#define USE_LAGUERRE ///< Remove this to skip the SBLaguerre classes.

#include "Std.h"
#include "Shear.h"
#include "FFT.h"
#include "Table.h"

#ifdef USE_IMAGES
#include "Image.h"
#endif

#ifdef USE_LAGUERRE
#include "Laguerre.h"
#endif

// ??? could += for SBAdd, or *= to SBConvolve
// ??? Ask for super-Nyquist sampling factor in draw??
namespace galsim {

    /// @brief Exception class thrown by SBProfiles.
    class SBError : public std::runtime_error 
    {
    public:
        SBError(const std::string& m="") : std::runtime_error("SB Error: " + m) {}
    };

    /** 
     * @brief An abstract base class representing all of the 2D surface brightness profiles that 
     * we know how to draw.
     *
     * Every SBProfile knows how to draw an Image<float> of itself in real and k space.  Each also
     * knows what is needed to prevent aliasing or truncation of itself when drawn.
     * **Note** that when you use the SBProfile::draw() routines you will get an image of 
     * **surface brightness** values in each pixel, not the flux that fell into the pixel.  To get
     * flux, you must multiply the image by (dx*dx).
     * drawK() routines are normalized such that I(0,0) is the total flux.
     * Currently we have the following possible implementations of SBProfile:
     * Basic shapes: SBBox, SBGaussian, SBExponential, SBAiry, SBSersic
     * SBLaguerre: Gauss-Laguerre expansion
     * SBDistort: affine transformation of another SBProfile
     * SBRotate: rotated version of another SBProfile
     * SBAdd: sum of SBProfiles
     * SBConvolve: convolution of other SBProfiles
     */
    class SBProfile 
    {
    protected:
        static const int MINIMUM_FFT_SIZE;///< Constant giving minimum FFT size we're willing to do.
        static const int MAXIMUM_FFT_SIZE;///< Constant giving maximum FFT size we're willing to do.
        /**
         * @brief A rough indicator of how good the FFTs need to be for setting `maxK()` and 
         * `stepK()` values.
         */
        static const double ALIAS_THRESHOLD;

    public:

        /** 
         * @brief Destructor (virtual) -- Constructor and Copy Constructor are automatically 
         * generated by compiler.
         */
        virtual ~SBProfile() {}                        

        //
        // implementation-dependent methods
        //

        /// @brief Return a copy of self.
        virtual SBProfile* duplicate() const =0;

       /** 
         * @brief Return value of SBProfile at a chosen 2D position in real space.
         *
         * Assume all are real-valued.
         * xValue() may not be implemented for derived classes (SBConvolve) that
         * require an FFT to determine real-space values.
         *
         * @param[in] _p 2D position in real space.
         */
        virtual double xValue(Position<double> _p) const =0;

       /**
         * @brief Return value of SBProfile at a chosen 2D position in k space.
         *
         * @param[in] _p 2D position in k space.
         */
        virtual std::complex<double> kValue(Position<double> _p) const =0; 

        virtual double maxK() const =0; ///< Value of k beyond which aliasing can be neglected.

        /// @brief Image pixel spacing that does not alias maxK.
        virtual double nyquistDx() const { return M_PI / maxK(); }

        /// @brief Sampling in k space necessary to avoid folding of image in x space.
        virtual double stepK() const =0;

        /// @brief Characteristic that can affect efficiency of evaluation.
        virtual bool isAxisymmetric() const =0;

        /** 
         * @brief Characteristic that can affect efficiency of evaluation.
         *
         * SBProfile is "analytic" in the real domain if values can be determined immediately at 
         * any position through formula or a stored table (no DFT).
         */
        virtual bool isAnalyticX() const =0; 

       /**
         * @brief Characteristic that can affect efficiency of evaluation.
         * 
         * SBProfile is "analytic" in the k domain if values can be determined immediately at any 
         * position through formula or a stored table (no DFT).
         */
        virtual bool isAnalyticK() const =0; 

        virtual double centroidX() const =0; ///<Centroid of SBProfile in x.
        virtual double centroidY() const =0; ///<Centroid of SBProfile in y.

        /// @brief Returns (X, Y) centroid of SBProfile.
        Position<double> centroid() const 
        { Position<double> p(centroidX(),centroidY());  return p; }


        virtual double getFlux() const =0; ///< Get flux scaling of SBProfile.

        /// @brief Set flux scaling of SBProfile
        //
        /// @param[in] flux_ flux
        virtual void setFlux(double flux_=1.) =0; ///< Set flux scaling of SBProfile.

        // ****Methods implemented in base class****

        // Transformations (all are special cases of affine transformations via SBDistort):

        /**
         * @brief Ellipse distortion transformation (affine without rotation).
         *
         * @param[in] e Ellipse class distortion.
         */
        virtual SBProfile* distort(const Ellipse e) const; 

        /** 
         * Shear distortion transformation (affine without rotation or dilation).
         *
         * @param[in] e1 first component of ellipticity.
         * @param[in] e2 second component of ellipticity.
         */
        virtual SBProfile* shear(double e1, double e2) const { return distort(Ellipse(e1,e2)); }
         
        /** 
         * @brief Rotation distortion transformation.
         *
         * @param[in] theta rotation, in radians, anticlockwise.
         */
        virtual SBProfile* rotate(const double theta) const;

       /**
         * Translation transformation.
         *
         * @param[in] dx shift in x.
         * @param[in] dy shift in y.
         */
        virtual SBProfile* shift(double dx, double dy) const;

#ifdef USE_IMAGES
        // **** Drawing routines ****


        /** 
	 * @brief Draw an image of the SBProfile in real space.
	 *
	 * A square image will be
         * drawn which is big enough to avoid "folding."  If drawing is done using FFT,
         * it will be scaled up to a power of 2, or 3x2^n, whicher fits.
         * If input image has finite dimensions then these will be used, although in an FFT the 
         * image  may be calculated internally on a larger grid to avoid folding.
         * The default draw() routines decide internally whether image can be drawn directly
         * in real space or needs to be done via FFT from k space.
	 *
         * @param[in] dx    grid on which SBProfile is drawn has pitch `dx`; given `dx=0.` default, 
	 *                  routine will choose `dx` to be at least fine enough for Nyquist sampling
	 *                  at `maxK()`.  If you specify dx, image will be drawn with this `dx` and
	 *                  you will receive an image with the aliased frequencies included.
         * @param[in] wmult specifying `wmult>1` will draw an image that is `wmult` times larger 
	 *                  than the default choice, i.e. it will have finer sampling in k space 
         *                  and have less folding.
	 * @returns image
	 */
        virtual Image<float> draw(double dx=0., int wmult=1) const;

        /** 
	 * @brief Draw the SBProfile in real space returning the summed flux.
         *
         * If on input image `img` is not specified or has null dimension, a square image will be
         * drawn which is big enough to avoid "folding."  If drawing is done using FFT,
         * it will be scaled up to a power of 2, or 3x2^n, whicher fits.
         * If input image has finite dimensions then these will be used, although in an FFT the 
         * image may be calculated internally on a larger grid to avoid folding.
	 * The default draw() routines decide internally whether image can be drawn directly
         * in real space or needs to be done via FFT from k space.
         *
         * @param[in,out]   image
         * @param[in] dx    grid on which SBProfile is drawn has pitch `dx`; given `dx=0.` default, 
	 *                  routine will choose `dx` to be at least fine enough for Nyquist sampling
	 *                  at `maxK()`.  If you specify dx, image will be drawn with this `dx` and
	 *                  you will receive an image with the aliased frequencies included.
         * @param[in] wmult specifying `wmult>1` will draw an image that is `wmult` times larger 
	 *                  than the default choice, i.e. it will have finer sampling in k space 
         *                  and have less folding.
	 * @returns summed flux.
	 */
        virtual double draw(Image<float> & image, double dx=0., int wmult=1) const; 

        /** 
	 * @brief Draw an image of the SBProfile in real space forcing the use of real methods 
	 * where we have a formula for x values.
         *
         * If on input image `img` is not specified or has null dimension, a square image will be
         * drawn which is big enough to avoid "folding." 
	 * If input image has finite dimensions then these will be used, although in an FFT the 
	 * image may be calculated internally on a larger grid to avoid folding.
         *
         * @param[in,out]   image
         * @param[in] dx    grid on which SBProfile is drawn has pitch `dx`; given `dx=0.` default, 
	 *                  routine will choose `dx` to be at least fine enough for Nyquist sampling
	 *                  at `maxK()`.  If you specify dx, image will be drawn with this `dx` and
	 *                  you will receive an image with the aliased frequencies included.
         * @param[in] wmult specifying `wmult>1` will draw an image that is `wmult` times larger 
	 *                  than the default choice, i.e. it will have finer sampling in k space 
         *                  and have less folding.
	 * @returns summed flux.
	 */
        virtual double plainDraw(Image<float> & image, double dx=0., int wmult=1) const; 

        /** 
	 * @brief Draw an image of the SBProfile in real space forcing the use of Fourier transform
	 * from k space.
         *
         * If on input image `img` is not specified or has null dimension, a square image will be
         * drawn which is big enough to avoid "folding."  Drawing is done using FFT,
         * and the image will be scaled up to a power of 2, or 3x2^n, whicher fits.
         * If input image has finite dimensions then these will be used, although in an FFT the 
         * image may be calculated internally on a larger grid to avoid folding.
         *
	 * @param[in,out]   image
         * @param[in] dx    grid on which SBProfile is drawn has pitch `dx`; given `dx=0.` default, 
	 *                  routine will choose `dx` to be at least fine enough for Nyquist sampling
	 *                  at `maxK()`.  If you specify dx, image will be drawn with this `dx` and
	 *                  you will receive an image with the aliased frequencies included.
         * @param[in] wmult specifying `wmult>1` will draw an image that is `wmult` times larger 
	 *                  than the default choice, i.e. it will have finer sampling in k space 
         *                  and have less folding.
	 * @returns summed flux.
	 */
        virtual double fourierDraw(Image<float> & image, double dx=0., int wmult=1) const; 

        /** 
	 * @brief Draw an image of the SBProfile in k space.
         *
         * For drawing in k space: routines are analagous to real space, except 2 images are 
	 * needed since the SBProfile is complex.
         * If on input either image `Re` or `Im` is not specified or has null dimension, square 
	 * images will be drawn which are big enough to avoid "folding."  If drawing is done using 
	 * FFT, they will be scaled up to a power of 2, or 3x2^n, whicher fits.
         * If input image has finite dimensions then these will be used, although in an FFT the 
	 * image may be calculated internally on a larger grid to avoid folding in real space.
         *
         * @param[in,out]   re image of real argument of SBProfile in k space.
         * @param[in,out]   im image of imaginary argument of SBProfile in k space.
         * @param[in] dk    grid on which SBProfile is drawn has pitch `dk`; given `dk=0.` default,
         *                  routine will choose `dk` necessary to avoid folding of image in real 
	 *                  space.  If you specify `dk`, image will be drawn with this `dk` and
	 *                  you will receive an image with folding artifacts included.
         * @param[in] wmult specifying `wmult>1` will expand the size drawn in k space.
	 */
        virtual void drawK(Image<float> & re, Image<float> & im, double dk=0., int wmult=1) const; 

        /** 
	 * @brief Draw an image of the SBProfile in k space forcing the use of k space methods 
	 * where we have a formula for k values.
         *
         * For drawing in k space: routines are analagous to real space, except 2 images are 
	 * needed since the SBProfile is complex.  If on input either image `Re` or `Im` is not 
	 * specified or has null dimension, square images will be drawn which are big enough to 
	 * avoid "folding."
         *
         * @param[in,out]   re image of real argument of SBProfile in k space.
         * @param[in,out]   im image of imaginary argument of SBProfile in k space.
         * @param[in] dk    grid on which SBProfile is drawn has pitch `dk`; given `dk=0.` default,
         *                  routine will choose `dk` necessary to avoid folding of image in real 
	 *                  space.  If you specify `dk`, image will be drawn with this `dk` and
	 *                  you will receive an image with folding artifacts included.
         * @param[in] wmult specifying `wmult>1` will expand the size drawn in k space.
	 */
        virtual void plainDrawK(
            Image<float> & re, Image<float> & im, 
            double dk=0., int wmult=1) const; 

        /**
         * @brief Draw an image of the SBProfile in k space forcing the use of Fourier transform 
	 * from real space.
         *
         * For drawing in k space: routines are analagous to real space, except 2 images are 
	 * needed since the SBProfile is complex.
         * If on input either image `Re` or `Im` is not specified or has null dimension, square 
	 * images will be drawn which are big enough to avoid "folding."  Drawing is done using FFT,
	 * and the images will be scaled up to a power of 2, or 3x2^n, whicher fits.
         * If input image has finite dimensions then these will be used, although in an FFT the 
         * image may be calculated internally on a larger grid to avoid folding in real space.
         *
         * @param[in,out]   re image of real argument of SBProfile in k space.
         * @param[in,out]   im image of imaginary argument of SBProfile in k space.
         * @param[in] dk    grid on which SBProfile is drawn has pitch `dk`; given `dk=0.` default,
         *                  routine will choose `dk` necessary to avoid folding of image in real 
	 *                  space.  If you specify `dk`, image will be drawn with this `dk` and
	 *                  you will receive an image with folding artifacts included.
         * @param[in] wmult specifying `wmult>1` will expand the size drawn in k space.
	 */
        virtual void fourierDrawK(
            Image<float> & re, Image<float> & im,
            double dk=0., int wmult=1) const; 

        /** 
	 * @brief Utility for drawing into Image data structures.
         *
         * @param[out] image    image to fill
         * @param[in]  dx       grid pitch on which SBProfile image is drawn
	 */
        virtual double fillXImage(Image<float> & image, double dx) const;  // return flux integral

#endif

       /**
        * @brief Utility for drawing a k grid into FFT data structures - not intended for public 
        * use, but need to be public so that derived classes can call them.
	*/
        virtual void fillKGrid(KTable& kt) const;
       /** 
        * @brief Utility for drawing an x grid into FFT data structures - not intended for public 
	* use, but need to be public so that derived classes can call them.
	*/
        virtual void fillXGrid(XTable& xt) const;

    };

    /** 
     * @brief Sums SBProfiles. 
     *
     * Note that this class stores duplicates of its summands,
     * so they cannot be changed after adding them.
     */
    class SBAdd : public SBProfile 
    {
    protected:
        /// @brief The plist content is a pointer to a fresh copy of the summands.
        std::list<SBProfile*> plist; 
    private:
        double sumflux; ///< Keeps track of the cumulated flux of all summands.
        double sumfx; ///< Keeps track of the cumulated `fx` of all summands.
        double sumfy; ///< Keeps track of the cumulated `fy` of all summands.
        double maxMaxK; ///< Keeps track of the cumulated `maxK()` of all summands.
        double minStepK; ///< Keeps track of the cumulated `minStepK()` of all summands.

        /// @brief Keeps track of the cumulated `isAxisymmetric()` properties of all summands.
        bool allAxisymmetric;

        /// @brief Keeps track of the cumulated `isAnalyticX()` property of all summands. 
        bool allAnalyticX; 

        /// @brief Keeps track of the cumulated `isAnalyticK()` properties of all summands.
        bool allAnalyticK; 

        void initialize();  ///< Sets all private book-keeping variables to starting state.

    public:
        /// @brief Constructor, empty.
        SBAdd() : plist() { initialize(); }

        /** 
	 * @brief Constructor, 1 input.
         *
         * @param[in] s1 SBProfile.
	 */
        SBAdd(const SBProfile& s1) : plist() { initialize(); add(s1); }

        /** @brief Constructor, 2 inputs.
	 *
         * @param[in] s1 first SBProfile.
         * @param[in] s2 second SBProfile.
	 */
        SBAdd(const SBProfile& s1, const SBProfile& s2) : plist() 
        { initialize(); add(s1);  add(s2); }

        /** 
	 * @brief Constructor, list of inputs.
         *
         * @param[in] slist list of SBProfiles.
	 */
        SBAdd(const std::list<SBProfile*> slist) : plist() 
        {
            std::list<SBProfile*>::const_iterator sptr;
            for (sptr = slist.begin(); sptr!=slist.end(); ++sptr)
                add(*(*sptr)->duplicate()); 
        }

        /** 
	 * @brief Copy constructor.
	 * @param[in] rhs SBAdd to be copied.
	 */
        SBAdd(const SBAdd& rhs) : 
            plist(), sumflux(rhs.sumflux), sumfx(rhs.sumfx),
            sumfy(rhs.sumfy), maxMaxK(rhs.maxMaxK), minStepK(rhs.minStepK), 
            allAxisymmetric(rhs.allAxisymmetric),
            allAnalyticX(rhs.allAnalyticX), allAnalyticK(rhs.allAnalyticK)  
        {
            std::list<SBProfile*>::const_iterator sbptr;
            for (sbptr = rhs.plist.begin(); sbptr!=rhs.plist.end(); ++sbptr)
                plist.push_back((*sbptr)->duplicate());
        }

        /// @brief Destructor.
        ~SBAdd() 
        { 
            std::list<SBProfile*>::iterator pptr;
            for (pptr = plist.begin(); pptr!=plist.end(); ++pptr)  delete *pptr; 
        }

        /** 
	 * @brief SBAdd specific method for adding additional SBProfiles
         *
         * @param[in] rhs SBProfile.
         * @param[in] scale allows for rescaling flux by this factor.
	 */
        void add(const SBProfile& rhs, double scale=1.);

        // Barney's note: the methods below are documented at the SBProfile level (I think)

        SBProfile* duplicate() const { return new SBAdd(*this); } 

        double xValue(Position<double> _p) const;

        std::complex<double> kValue(Position<double> _p) const;

        double maxK() const { return maxMaxK; }
        double stepK() const { return minStepK; }

        bool isAxisymmetric() const { return allAxisymmetric; }
        bool isAnalyticX() const { return allAnalyticX; }
        bool isAnalyticK() const { return allAnalyticK; }

        virtual double centroidX() const { return sumfx / sumflux; }
        virtual double centroidY() const { return sumfy / sumflux; }

        virtual double getFlux() const { return sumflux; }
        virtual void setFlux(double flux_=1.);

        // Overrides for better efficiency:
        virtual void fillKGrid(KTable& kt) const;
        virtual void fillXGrid(XTable& xt) const;
    };

    /**
     * @brief An affine transformation of another SBProfile.
     *
     * Stores a duplicate of its target.
     * Origin of original shape will now appear at `x0`.
     * Flux is NOT conserved in transformation - surface brightness is preserved.
     * We keep track of all distortions in a 2x2 matrix `M = [(A B), (C D)]` = [row1, row2] 
     * (det`M`=1), with an additional determinant multiplier `absdet`, plus a 2-element `x0` for
     * the shift.
     */
    class SBDistort : public SBProfile 
    {
        
    private:
        SBProfile* adaptee; ///< SBProfile being adapted/distorted
        double matrixA; ///< A element of 2x2 distortion matrix `M = [(A B), (C D)]` = [row1, row2]
        double matrixB; ///< B element of 2x2 distortion matrix `M = [(A B), (C D)]` = [row1, row2]
        double matrixC; ///< C element of 2x2 distortion matrix `M = [(A B), (C D)]` = [row1, row2]
        double matrixD; ///< D element of 2x2 distortion matrix `M = [(A B), (C D)]` = [row1, row2]
        // Calculate and save these:
        Position<double> x0;  ///< Centroid position.
        double absdet;  ///< Determinant (flux magnification) of `M` matrix.
        double invdet;  ///< Inverse determinant of `M` matrix.
        double major; ///< Major axis of ellipse produced from unit circle.
        double minor; ///< Minor axis of ellipse produced from unit circle.
        bool stillIsAxisymmetric; ///< Is output SBProfile shape still circular?

    private:
        /// @brief Initialize the SBDistort.
        void initialize();

        /** 
	 * @brief Forward coordinate transform with `M` matrix.
	 *
	 * @param[in] p input position.
	 * @returns transformed position.
	 */
        Position<double> fwd(Position<double> p) const 
        {
            Position<double> out(matrixA*p.x+matrixB*p.y,matrixC*p.x+matrixD*p.y);
            return out; 
        }

        /// @brief Forward coordinate transform with transpose of `M` matrix.
        Position<double> fwdT(Position<double> p) const 
        {
            Position<double> out(matrixA*p.x+matrixC*p.y,matrixB*p.x+matrixD*p.y);
            return out; 
        }

        /// @brief Inverse coordinate transform with `M` matrix.
        Position<double> inv(Position<double> p) const 
        {
            Position<double> out(invdet*(matrixD*p.x-matrixB*p.y),
                                 invdet*(-matrixC*p.x+matrixA*p.y));
            return out; 
        }

        /// @brief Returns the the k value (no phase).
        std::complex<double> kValNoPhase(Position<double> k) const 
        { return absdet*adaptee->kValue(fwdT(k)); }


    public:
        /** 
	 * @brief General constructor.
         *
         * @param[in] sbin SBProfile being distorted
         * @param[in] mA A element of 2x2 distortion matrix `M = [(A B), (C D)]` = [row1, row2]
         * @param[in] mB B element of 2x2 distortion matrix `M = [(A B), (C D)]` = [row1, row2]
         * @param[in] mC C element of 2x2 distortion matrix `M = [(A B), (C D)]` = [row1, row2]
         * @param[in] mD D element of 2x2 distortion matrix `M = [(A B), (C D)]` = [row1, row2]
         * @param[in] x0_ 2-element (x, y) Position for the translational shift.
	 */
        SBDistort(
            const SBProfile& sbin, double mA, double mB, double mC, double mD,
            Position<double> x0_=Position<double>(0.,0.));

        /** 
	 * @brief Construct from an input Ellipse class object
         *
         * @param[in] sbin SBProfile being distorted.
         * @param[in] e_ Ellipse.
	 */
        SBDistort(const SBProfile& sbin, const Ellipse e_=Ellipse());

        /** 
	 * @brief Copy constructor
         *
         * @param[in] rhs SBProfile being copied.
	 */
        SBDistort(const SBDistort& rhs) 
        {
            adaptee = rhs.adaptee->duplicate();
            matrixA = (rhs.matrixA); 
            matrixB = (rhs.matrixB); 
            matrixC = (rhs.matrixC);
            matrixD = (rhs.matrixD); 
            x0 = (rhs.x0);
            initialize();
        }

        /// @brief Destructor.
        ~SBDistort() { delete adaptee; adaptee=0; }

        // methods doxy described in base clase SBProfile
        SBProfile* duplicate() const 
        { return new SBDistort(*this); } 

        double xValue(Position<double> p) const 
        { return adaptee->xValue(inv(p-x0)); }

        std::complex<double> kValue(Position<double> k) const 
        {
            std::complex<double> phaseexp(0,-k.x*x0.x-k.y*x0.y); // phase exponent
            std::complex<double> kv(absdet*adaptee->kValue(fwdT(k))*exp(phaseexp));
            return kv; 
        }

        bool isAxisymmetric() const { return stillIsAxisymmetric; }
        bool isAnalyticX() const { return adaptee->isAnalyticX(); }
        bool isAnalyticK() const { return adaptee->isAnalyticK(); }

        double maxK() const { return adaptee->maxK() / minor; }
        double stepK() const { return adaptee->stepK() / major; }

        double centroidX() const { return (x0+fwd(adaptee->centroid())).x; }
        double centroidY() const { return (x0+fwd(adaptee->centroid())).y; }

        double getFlux() const { return adaptee->getFlux()*absdet; }
        void setFlux(double flux_=1.) { adaptee->setFlux(flux_/absdet); }

        void fillKGrid(KTable& kt) const; // optimized phase calculation
    };

    /// Convolve SBProfiles.
    //
    /// Convolve one, two, three or more SBProfiles together (TODO: Add a more detailed description here).
    class SBConvolve : public SBProfile 
    {
    private:
        std::list<SBProfile*> plist;  ///< The plist content is a copy_ptr (cf. smart ptrs) listing SBProfiles.
        double fluxScale; ///< Flux scaling.
        double x0; ///< Centroid position in x.
        double y0; ///< Centroid position in y.
        bool isStillAxisymmetric; ///< Is output SBProfile shape still circular?
        double minMaxK; ///< Minimum maxK() of the convolved SBProfiles.
        double minStepK; ///< Minimum stepK() of the convolved SBProfiles.
        double fluxProduct; ///< Flux of the product.

    public:
        /// Constructor, empty.
        SBConvolve() : plist(), fluxScale(1.) {} 

        /// Constructor, 1 input.
        //
        /// @param s1 Input: SBProfile.
        /// @param f Input: optional scaling factor for final flux (default `f = 1.`).
        SBConvolve(const SBProfile& s1, double f=1.) : plist(), fluxScale(f) 
        { add(s1); }

        /// Constructor, 2 inputs.
        //
        /// @param s1 Input: first SBProfile.
        /// @param s2 Input: second SBProfile.
        /// @param f Input: optional scaling factor for final flux (default `f = 1.`).
        SBConvolve(const SBProfile& s1, const SBProfile& s2, double f=1.) : 
            plist(), fluxScale(f) 
        { add(s1);  add(s2); }

        /// Constructor, 3 inputs.
        //
        /// @param s1 Input: first SBProfile.
        /// @param s2 Input: second SBProfile.
        /// @param s3 Input: third SBProfile.
        /// @param f Input: optional scaling factor for final flux (default `f = 1.`).
        SBConvolve(
            const SBProfile& s1, const SBProfile& s2, const SBProfile& s3, double f=1.) :
            plist(), fluxScale(f) 
        { add(s1);  add(s2);  add(s3); }

        /// Constructor, list of inputs.
        //
        /// @param slist Input: list of SBProfiles.
        /// @param f Input: optional scaling factor for final flux (default `f = 1.`).
        SBConvolve(const std::list<SBProfile*> slist, double f=1.) :
            plist(), fluxScale(f) 
        { 
            std::list<SBProfile*>::const_iterator sptr;
            for (sptr = slist.begin(); sptr!=slist.end(); ++sptr) add(**sptr); 
        }

        /// Copy constructor.
        //
        /// @param rhs Input: SBProfile.
        SBConvolve(const SBConvolve& rhs) : 
            plist(), fluxScale(rhs.fluxScale),
            x0(rhs.x0), y0(rhs.y0),
            isStillAxisymmetric(rhs.isStillAxisymmetric),
            minMaxK(rhs.minMaxK), minStepK(rhs.minStepK),
            fluxProduct(rhs.fluxProduct) 
        {
            std::list<SBProfile*>::const_iterator rhsptr;
            for (rhsptr = rhs.plist.begin(); rhsptr!=rhs.plist.end(); ++rhsptr)
                plist.push_back((*rhsptr)->duplicate()); 
        }

        /// Destructor.
        ~SBConvolve() 
        { 
            std::list<SBProfile*>::iterator pptr;
            for (pptr = plist.begin(); pptr!=plist.end(); ++pptr)  delete *pptr; 
        }

        /// SBConvolve specific method for adding new members.
        //
        /// @param rhs Input: SBProfile for adding.
        void add(const SBProfile& rhs); 

        // Barney's note: I think the methods below are documented at the SBProfile level

        // implementation dependent methods:
        SBProfile* duplicate() const { return new SBConvolve(*this); } 

        double xValue(Position<double> _p) const 
        { throw SBError("SBConvolve::xValue() not allowed"); } 

        std::complex<double> kValue(Position<double> k) const 
        {
            std::list<SBProfile*>::const_iterator pptr;
            std::complex<double> product(fluxScale,0);
            for (pptr=plist.begin(); pptr!=plist.end(); ++pptr)
                product *= (*pptr)->kValue(k);
            return product; 
        }

        bool isAxisymmetric() const { return isStillAxisymmetric; }
        bool isAnalyticX() const { return false; }
        bool isAnalyticK() const { return true; }    // convolvees must all meet this
        double maxK() const { return minMaxK; }
        double stepK() const { return minStepK; }
        double centroidX() const { return x0; }
        double centroidY() const { return y0; }
        double getFlux() const { return fluxScale * fluxProduct; }
        void setFlux(double flux_=1.) { fluxScale = flux_/fluxProduct; }

        // Overrides for better efficiency:
        virtual void fillKGrid(KTable& kt) const;
    };

    /// Gaussian Surface Brightness Profile
    //
    /// The Gaussian Surface Brightness Profile is characterized by two properties, its `flux`
    /// and the characteristic size `sigma` where the radial profile of the circular Gaussian
    /// drops off as `exp[-r^2 / (2. * sigma^2)]`.
    /// The maxK() and stepK() are for the SBGaussian are chosen to extend to 4 sigma in both 
    /// real and k domains, or more if needed to reach the `ALIAS_THRESHOLD` spec.
    class SBGaussian : public SBProfile 
    {
    private:
        double flux; ///< Flux of the Surface Brightness Profile.
        double sigma; ///< Characteristic size, surface brightness scales as `exp[-r^2 / (2. * sigma^2)]`.

    public:
        /// Constructor
        //
        /// @param flux_ Input: flux of the Surface Brightness Profile (default `flux_ = 1.`).
        /// @param sigma_ Input: characteristic size, surface brightness scales as `exp[-r^2 / (2. * sigma^2)] (default `sigma_ = 1.`).
        SBGaussian(double flux_=1., double sigma_=1.) : flux(flux_), sigma(sigma_) {}

        /// Destructor
        ~SBGaussian() {}                        

        double xValue(Position<double> _p) const;
        std::complex<double> kValue(Position<double> _p) const;

        bool isAxisymmetric() const { return true; } 
        bool isAnalyticX() const { return true; }
        bool isAnalyticK() const { return true; }

        // Extend to 4 sigma in both domains, or more if needed to reach EE spec
        double maxK() const { return std::max(4., sqrt(-2.*log(ALIAS_THRESHOLD))) / sigma; }
        double stepK() const { return M_PI/std::max(4., sqrt(-2.*log(ALIAS_THRESHOLD))) / sigma; }
        double centroidX() const { return 0.; } 
        double centroidY() const { return 0.; } 
        double getFlux() const { return flux; }
        void setFlux(double flux_=1.) { flux=flux_; }
        SBProfile* duplicate() const { return new SBGaussian(*this); }
    };

    /// Sersic Surface Brightness Profile.
    //
    /// The Sersic Surface Brightness Profile is characterized by three properties: its Sersic 
    /// index `n`, its `flux` and the half-light radius `re`.
    class SBSersic : public SBProfile 
    {
    private:
        /// A private class that caches the needed parameters for each Sersic index `n`.
        class SersicInfo 
        {
        public:
            SersicInfo(double n); ///< This class contains all the info needed to calculate values for a given Sersic index `n`.  
            double inv2n;   ///< `1 / (2 * n)`
            double maxK;    ///< Value of k beyond which aliasing can be neglected.
            double stepK;   ///< Sampling in k space necessary to avoid folding of image in x space.
            double xValue(double xsq) const { return norm*exp(-b*pow(xsq,inv2n)); } ///< Returns the real space value of the Sersic using the formula `exp(-b*pow(xsq,inv2n))` (see private attributes).
            double kValue(double ksq) const; ///< Looks up the k value for the SBProfile from a lookup table.

        private:
            SersicInfo(const SersicInfo& rhs) {} ///< Hides the copy constructor.
            double b; ///< Scaling in Sersic profile `exp(-b*pow(xsq,inv2n))`, calculated from Sersic index `n` and half-light radius `re`.
            double norm; ///< Amplitude scaling in Sersic profile `exp(-b*pow(xsq,inv2n))`.
            double kderiv2; ///< Quadratic dependence near k=0.
            double kderiv4; ///< Quartic dependence near k=0.
            double logkMin; ///< Minimum log(k) in lookup table.
            double logkMax; ///< Maximum log(k) in lookup table.
            double logkStep; ///< Stepsize in log(k) in lookup table.
            std::vector<double> lookup; ///< Lookup table.
        };

        /// A map to hold one copy of the SersicInfo for each `n` ever used during the program run.  Make one static copy of this map.
        class InfoBarn : public std::map<double, const SersicInfo*> 
        {
        public:

	    /// Get the SersicInfo table for a specified `n`.
            //
            /// @param n Input: Sersic index for which the information table is required.
            const SersicInfo* get(double n) 
            {
                const int MAX_SERSIC_TABLES = 100; /// Contains `MAX_SERSIC_TABLES = 100`, the currently hardwired max number of Sersic `n` info tables that can be stored.  Should be plenty.
                const SersicInfo* info = (*this)[n];
                if (info==0) {
                    info = new SersicInfo(n);
                    (*this)[n] = info;
                    if (int(size()) > MAX_SERSIC_TABLES)
                        throw SBError("Storing Sersic info for too many n values");
                }
                return info;
            }
            /// Destructor.
            ~InfoBarn() 
            {
                typedef std::map<double,const SersicInfo*>::iterator mapit;
                for (mapit pos = begin(); pos != end(); ++pos) {
                    delete pos->second;
                    pos->second = 0;
                }
            }
        };
        static InfoBarn nmap;

        // Now the parameters of this instance of SBSersic:
        double n; ///< Sersic index.
        double flux; ///< Flux.
        double re;   ///< Half-light radius.
        const SersicInfo* info; // point to info structure for this n

    public:
        /// Constructor.
        //
        /// @param n_ Input: Sersic index.
        /// @param flux_ Input: flux (default `flux_ = 1.`).
        /// @param re_ Input: half-light radius (default `re_ = 1.`).
        SBSersic(double n_, double flux_=1., double re_=1.) :
            n(n_), flux(flux_), re(re_), info(nmap.get(n)) {}

        // Default copy constructor should be fine.

        /// Destructor
        ~SBSersic() {}

        // Barney note: methods below already doxyfied via SBProfile, except for getN

        double xValue(Position<double> p) const 
        {
            p /= re;
            return flux*info->xValue(p.x*p.x+p.y*p.y) / (re*re);
        }

        std::complex<double> kValue(Position<double> k) const 
        {
            k *= re;
            return std::complex<double>( flux*info->kValue(k.x*k.x+k.y*k.y), 0.);
        }

        bool isAxisymmetric() const { return true; }
        bool isAnalyticX() const { return true; }
        bool isAnalyticK() const { return true; }  // 1d lookup table

        double maxK() const { return info->maxK / re; }
        double stepK() const { return info->stepK / re; }

        double centroidX() const { return 0.; } 
        double centroidY() const { return 0.; } 

        double getFlux() const { return flux; }
        void setFlux(double flux_=1.) { flux=flux_; }

        SBProfile* duplicate() const { return new SBSersic(*this); }

        /// A method that only works for Sersic, returns the Sersic index `n`.
        double getN() const { return n; }
    };

    /// Exponential Surface Brightness Profile.  
    //
    /// This is a special case of the Sersic profile, but is given a separate class since the 
    /// Fourier transform has closed form and can be generated without lookup tables.
    /// The maxK() is set to where the FT is down to 0.001, or via `ALIAS_THRESHOLD`, whichever is harder.
    class SBExponential : public SBProfile 
    {
    private:
        double r0;   ///< Characteristic size of profile `exp[-(r / r0)]`.
        double flux; ///< Flux.
    public:
        /// Constructor - note that `r0` is scale length, NOT half-light radius `re` as in SBSersic.
        //
        /// @param flux_ Input: flux (default `flux_ = 1.`).
        /// @param r0_ Input: scale length for the profile that scales as `exp[-(r / r0)]`, NOT the half-light radius `re` as in SBSersic (default `r0_ = 1.`).
        SBExponential(double flux_=1., double r0_=1.) : r0(r0_), flux(flux_) {}

        /// Destructor.
        ~SBExponential() {}

        // Methods
        double xValue(Position<double> _p) const;
        std::complex<double> kValue(Position<double> _p) const;

        bool isAxisymmetric() const { return true; } 
        bool isAnalyticX() const { return true; }
        bool isAnalyticK() const { return true; }

        // Set maxK where the FT is down to 0.001 or threshold, whichever is harder.
        double maxK() const { return std::max(10., pow(ALIAS_THRESHOLD, -1./3.))/r0; }
        double stepK() const;

        double centroidX() const { return 0.; } 
        double centroidY() const { return 0.; } 

        double getFlux() const { return flux; }
        void setFlux(double flux_=1.) { flux=flux_; }

        SBProfile* duplicate() const { return new SBExponential(*this); }
    };

    /// Surface Brightness Profile for the Airy disk (perfect diffraction-limited PSF for a circular aperture), with central obscuration.
    //
    /// maxK() is set at the hard limit for Airy disks, stepK() makes transforms go to at least 
    /// 5 lam/D or EE>(1-ALIAS_THRESHOLD).  Schroeder (10.1.18) gives limit of EE at large radius.
    /// This stepK could probably be relaxed, it makes overly accurate FFTs.
    /// Note x & y are in units of lambda/D here.  Integral over area
    /// will give unity in this normalization.
    class SBAiry : public SBProfile 
    {
    private:
        double D;    ///< `D` = (telescope diam) / (lambda * focal length) if arg is focal plane position, else `D` = (telescope diam) / lambda if arg is in radians of field angle.
        double obscuration; ///< Radius ratio of central obscuration.
        double flux; ///< Flux.

    public:
        /// Constructor.
        //
        /// @param D_ Input: `D` = (telescope diam) / (lambda * focal length) if arg is focal plane position, else `D` = (telescope diam) / lambda if arg is in radians of field angle (default `D_ = 1.`).
        /// @param obs_ Input: radius ratio of central obscuration (default `obs_ = 0.`).
        /// @param flux_ Input: flux (default `flux_ = 1.`).
        SBAiry(double D_=1., double obs_=0., double flux_=1.) :
            D(D_), obscuration(obs_), flux(flux_) {}

        /// Destructor.
        ~SBAiry() {}

        // Methods (Barney: mostly described by SBProfile Doxys, with maxK() and stepK() 
        // prescription described in class description).
        double xValue(Position<double> _p) const;
        std::complex<double> kValue(Position<double> _p) const;

        bool isAxisymmetric() const { return true; } 
        bool isAnalyticX() const { return true; }
        bool isAnalyticK() const { return true; }

        double maxK() const { return 2*M_PI*D; } ///< Set at hard limit for Airy disk.

        // stepK makes transforms go to at least 5 lam/D or EE>(1-ALIAS_THRESHOLD).
        // Schroeder (10.1.18) gives limit of EE at large radius.
        // This stepK could probably be relaxed, it makes overly accurate FFTs.
        double stepK() const 
        { 
            return std::min( 
                ALIAS_THRESHOLD * 0.5 * D * pow(M_PI,3.) * (1-obscuration) ,
                M_PI * D / 5.);
        }
        double centroidX() const { return 0.; } 
        double centroidY() const { return 0.; } 

        double getFlux() const { return flux; }
        void setFlux(double flux_=1.) { flux=flux_; }

        SBProfile* duplicate() const { return new SBAiry(*this); }

    private: 
        double chord(const double r, const double h) const; ///< Circle chord length at `h < r`.
        double circle_intersection(
				   double r, double s, double t) const; ///< Area inside intersection of 2 circles radii `r` & `s`, seperated by `t`.
        double annuli_intersect(
				double r1, double r2, double t) const; ///< Area of two intersecting identical annuli.
        double annuli_autocorrelation(const double k) const; ///< Beam pattern of annular aperture, in k space, which is just the autocorrelation of two annuli.  Normalized to unity at `k=0` for now.
    };

    /// Surface Brightness Profile for the Boxcar function.
    //
    /// Convolution with a Boxcar function of dimensions `xw` x `yw` and sampling at pixel centres
    /// is equivalent to pixelation (i.e. Surface Brightness integration) across rectangular pixels
    /// of the same dimensions.  This class is therefore useful for pixelating SBProfiles. 
    class SBBox : public SBProfile 
    {
    private:
        double xw;   ///< Boxcar function is `xw` x `yw` across.
        double yw;   ///< Boxcar function is `xw` x `yw` across.
        double flux; ///< Flux.
        double sinc(const double u) const; ///< Sinc function used to describe Boxcar in k space. @param u Input: Normalized wavenumber.
    public:
        /// Constructor.
        //
        /// @param xw_ Input: width of Boxcar function along x (default `xw_ = 1.`).
        /// @param yw_ Input: width of Boxcar function along y (default `yw_ = 0.`).
        /// @param flux_ Input: flux (default `flux_ = 1.`).
        SBBox(double xw_=1., double yw_=0., double flux_=1.) :
            xw(xw_), yw(yw_), flux(flux_) 
        { if (yw==0.) yw=xw; }

        /// Destructor.
        ~SBBox() {}

        // Methods (Barney: public methods Doxified via SBProfile).
        double xValue(Position<double> _p) const;
        std::complex<double> kValue(Position<double> _p) const;

        bool isAxisymmetric() const { return false; } 
        bool isAnalyticX() const { return true; }
        bool isAnalyticK() const { return true; }

        double maxK() const { return 2. / ALIAS_THRESHOLD / std::max(xw,yw); }  
        double stepK() const { return M_PI/std::max(xw,yw)/2; } 

        double centroidX() const { return 0.; } 
        double centroidY() const { return 0.; } 

        double getFlux() const { return flux; }
        void setFlux(double flux_=1.) { flux=flux_; }

        SBProfile* duplicate() const { return new SBBox(*this); }

        // Override to put in fractional edge values:
        void fillXGrid(XTable& xt) const;

    protected:
#ifdef USE_IMAGES
        double fillXImage(Image<float> I, double dx) const;
#endif
    };

#ifdef USE_LAGUERRE
    /// Class for describing Gauss-Laguerre polynomial Surface Brightness Profiles.
    class SBLaguerre : public SBProfile 
    {
    private:
        LVector bvec;  ///< `bvec[n,n]` contains flux information for the `(n, n)` basis function.
        double sigma;  ///< Scale size of Gauss-Laguerre basis set.
    public:
        /// Constructor.
        //
        /// @param bvec_ Input: `bvec[n,n]` contains flux information for the `(n, n)` basis function.
        /// @param sigma_ Input: scale size of Gauss-Laguerre basis set (default `sigma_ = 1.`).
        SBLaguerre(LVector bvec_=LVector(), double sigma_=1.) : 
            bvec(bvec_.duplicate()), sigma(sigma_) {}

        /// Copy Constructor. 
        SBLaguerre(const SBLaguerre& rhs) :
            bvec(rhs.bvec.duplicate()), sigma(rhs.sigma) {}

        /// Destructor. 
        ~SBLaguerre() {}

        // implementation dependent methods
        SBProfile* duplicate() const { return new SBLaguerre(*this); }

        double xValue(Position<double> _p) const;
        std::complex<double> kValue(Position<double> _p) const;

        double maxK() const;
        double stepK() const;

        bool isAxisymmetric() const { return false; }
        bool isAnalyticX() const { return true; }
        bool isAnalyticK() const { return true; }

        double centroidX() const 
        { throw SBError("SBLaguerre::centroid calculations not yet implemented"); }
        double centroidY() const 
        { throw SBError("SBLaguerre::centroid calculations not yet implemented"); }

        double getFlux() const;
        void setFlux(double flux_=1.);

        // void fillKGrid(KTable& kt) const;
        // void fillXGrid(XTable& xt) const;

    };
#endif

    /// Surface Brightness for the Moffat Profile (an approximate description of ground-based PSFs).
    class SBMoffat : public SBProfile 
    {
    private:
        double beta; ///< Moffat beta parameter for profile `[1 + (r / rD)^2]^beta`.
        double flux; ///< Flux.
        double norm; ///< Normalization.
        double rD;   ///< Scale radius for profile `[1 + (r / rD)^2]^beta`.
        // In units of rD:
        double maxRrD; ///< Maximum `r` in units of `rD`.
        double maxKrD; ///< Maximum lookup table `k` in units of `rD`.
        double stepKrD; ///< Stepsize lookup table `k` in units of `rD`.
        double FWHMrD;  ///< Full Width at Half Maximum corresponding to `rD`.
        double rerD;    ///< Half-light radius corresponding to `rD`.

        Table<double,double> ft;  ///< Lookup table for Fourier transform of Moffat.

    public:
        /// Constructor.
        //
        /// @param beta_ Input: Moffat beta parameter for profile `[1 + (r / rD)^2]^beta`.
        /// @param truncationFWHM Input: outer truncation in units of FWHM (default `truncationFWHM = 2.`).
        /// @param flux_ Input: Flux (default `flux_ = 1.`).
        /// @param re Input: Half-light radius (default `re = 1.`).
        SBMoffat(
            double beta_, double truncationFWHM=2., double flux_=1., double re=1.);

        // Default copy constructor should be fine.

        /// Destructor.
        ~SBMoffat() {}

        double xValue(Position<double> p) const 
        {
            p /= rD;
            double rsq = p.x*p.x+p.y*p.y;
            if (rsq >= maxRrD*maxRrD) return 0.;
            else return flux*norm*pow(1+rsq, -beta) / (rD*rD);
        }

        std::complex<double> kValue(Position<double> k) const; 

        bool isAxisymmetric() const { return true; } 
        bool isAnalyticX() const { return true; }
        bool isAnalyticK() const { return true; }  // 1d lookup table

        double maxK() const { return maxKrD / rD; }   
        double stepK() const { return stepKrD / rD; } 

        double centroidX() const { return 0.; } 
        double centroidY() const { return 0.; } 

        double getFlux() const { return flux; }
        void setFlux(double flux_=1.) { flux=flux_; }

        SBProfile* duplicate() const { return new SBMoffat(*this); }

        // Methods that only work for Moffat:

        /// Returns the Moffat beta parameter for profile `[1 + (r / rD)^2]^beta`.
        double getBeta() const { return beta; }

        /// Set the FWHM. @param fwhm Input: new FWHM.
        void setFWHM(double fwhm) { rD = fwhm / FWHMrD; }
 
        /// Set the Moffat scale radius for profile `[1 + (r / rD)^2]^beta`. @param rD_ Input: new `rD`.
        void setRd(double rD_) { rD = rD_; }
    };


    /// This class is for backwards compatibility; prefer rotate() method.
    class SBRotate : public SBDistort 
    {
    public:
        // constructor #1

        /// Constructor.
        //
        /// @param s Input: SBProfile being rotated.
        /// @param theta Input: Rotation angle in radians anticlockwise.
        SBRotate(const SBProfile& s, const double theta) :
            SBDistort(s, cos(theta), -sin(theta), sin(theta), cos(theta)) {}
    };

    /// Surface Brightness for the de Vaucouleurs Profile, a special case of the Sersic with `n = 4`.
    class SBDeVaucouleurs : public SBSersic 
    {
    public:
        /// Constructor.
        //
        /// @param flux_ Input: flux (default `flux_ = 1.`).
        /// @param r0_ Input: Half-light radius (default `r0_ = 1.`).
        SBDeVaucouleurs(double flux_=1., double r0_=1.) : SBSersic(4., flux_, r0_) {}

        /// Destructor.
        ~SBDeVaucouleurs() {}

        SBProfile* duplicate() const { return new SBDeVaucouleurs(*this); }
    };


}

#endif // SBPROFILE_H

